#define SIMPLE_CHAR_IOC_MAGIC 'k'
#define SIMPLE_CHAR_IOC_MAXNR 4
#define SIMPLE_CHAR_CLEAR _IO(SIMPLE_CHAR_IOC_MAGIC, 0)
#define SIMPLE_CHAR_SET_SIZE _IOW(SIMPLE_CHAR_IOC_MAGIC, 1, int)
#define SIMPLE_CHAR_GET_SIZE _IOR(SIMPLE_CHAR_IOC_MAGIC, 2, int)
#define SIMPLE_CHAR_TELL_SIZE _IOW(SIMPLE_CHAR_IOC_MAGIC, 3, int)
#define SIMPLE_CHAR_EXCHANGE_SIZE _IOWR(SIMPLE_CHAR_IOC_MAGIC, 4, int)

#define BUFFER_SIZE 1024